services:

  # Servicio para la base de datos
  database:
    build:
      context: .
      dockerfile: Dockerfile
    image: carlosmz87/practica_sog_database:latest
    container_name: practica_sog_database_container
    volumes:
      - practica_sog_data:/var/lib/mysql
    networks:
      - practicaSOG_external_network
    ports:
      - "3306:${DATABASE_PORT}"
    env_file:
      - .env
  
volumes:
  practica_sog_data:

networks:
  practicaSOG_external_network:
    external: true 